import Head from 'next/head'
import Link from 'next/link'
import React,{useState,useEffect} from 'react'
import { createPost } from '../helper/fetchData'
import { useRouter } from 'next/router';
import { isAuthincated } from '../helper/auth'

export default function createNews() {
  const [data, setData] = useState('')
  const router = useRouter();

  const handleChang = (name) => event =>{
    setData({...data, [name]: event.target.value})
  }

  useEffect(() => { 
    if (!isAuthincated()) {
         router.push('/login')
    }
  }, [])

  function handleSubmit(e) {
    console.log(data)
    createPost({data})
    .then(res => {
      console.log(res);
      if(res.success){
        return router.push({
          pathname: '/',
      });
      }
    })
  }

  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main >
      <div style={{backgroundColor : "#202022", height : "100vh", textAlign : "center",alignItems : "center"}}>
                <ul>
                  <li>
                    <Link href="/login">
                      <a style={{backgroundColor : "red"}} >Log Out</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/About">
                      <a>About</a>
                    </Link>    
                  </li>
                  <li>
                    <Link href="/Contact">
                      <a >Help</a>
                    </Link> 
                   </li>
                  <li>
                    <Link href="/Profile">
                      <a >Profile</a>
                    </Link> 
                  </li>
                  <li>
                    <Link href="/createPost">
                      <a className='active'>Create Post</a>
                    </Link></li>
                  <li>
                    <Link href="/">
                      <a >Home</a>
                    </Link>
                  </li>
                </ul>
       <div style={{marginLeft : "50px",paddingTop : "70px",}}>
       <p style={{marginTop : 0,color : "#fff",fontFamily : "poppins", fontSize : 30}}>{`Create News`}</p>

       <div>
         <input 
           style={{backgroundColor : "#686868bf",
           border : "none",
           outline : "none",
           color : "white",
           width : "40%",
           padding : "10px",
           marginBottom : "10px",
           borderRadius : "5px",
         }}
         placeholder={"Title of the news"} 
         onChange={handleChang('title')}
         value={data.title}
         />
       </div>
       <textarea 
         style={{backgroundColor : "#686868bf",
         border : "none",
         outline : "none",
         color : "white",
         width : "40%",
         padding : "10px",
         marginBottom : "10px",
         borderRadius : "5px"
       }}
       rows={10}
       placeholder={"Write the news here"} 
       onChange={handleChang('news')}
       value={data.news}
       />
      <div>
        <button style={{padding : 10, backgroundColor : "black",border : "none",borderRadius : 5,cursor : "pointer"}} onClick={() => handleSubmit()} ><span style={{color : "white"}}>Send</span></button>
      </div>
     </div>
     </div>
    </main>
    </div>
  )
}
