import Head from 'next/head'
import React,{useState,useEffect} from 'react'
import { createUser } from '../helper/auth'
import { useRouter } from 'next/router';
import { isAuthincated } from '../helper/auth'

function createUserPage() {
    const [data, setData] = useState('')
    const router = useRouter();
    const handleChang = (name) => event =>{
    setData({...data, [name]: event.target.value})
    }

    // useEffect(() => {
    //   if (!isAuthincated()) {
    //        router.push('/login')
    //   }
    // }, [])

    function handleSubmit(e) {
    console.log(data)
    createUser({data})
    .then(res => {
      console.log(res);
    
      if(res.success){
        return router.push({
          pathname: '/login',
      });
      }
    })
  }
  return (
    <div>
        <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
      </Head>
      <main >
        <div style={{backgroundColor : "#202022", height : "100vh", textAlign : "center",alignItems : "center"}}> 
        <div style={{marginLeft : "50px",paddingTop : "70px",}}>
        <p style={{marginTop : 0,color : "#fff",fontFamily : "poppins", fontSize : 30}}>{`Login User`}</p>

        <div>
        <input 
           style={{backgroundColor : "#686868bf",
           border : "none",
           outline : "none",
           color : "white",
           width : "20%",
           padding : "10px",
           marginBottom : "10px",
           borderRadius : "5px",
         }}
         placeholder={"First Name"} 
         onChange={handleChang('firstName')}
         />
       </div>
       <div>
        <input 
            style={{backgroundColor : "#686868bf",
            border : "none",
            outline : "none",
            color : "white",
            width : "20%",
            padding : "10px",
            marginBottom : "10px",
            borderRadius : "5px",
            }}
            placeholder={"Last Name"} 
            onChange={handleChang('lastName')}
            />
       </div>
       <div>
        <input 
            style={{backgroundColor : "#686868bf",
            border : "none",
            outline : "none",
            color : "white",
            width : "20%",
            padding : "10px",
            marginBottom : "10px",
            borderRadius : "5px",
            }}
            placeholder={"Address"} 
            onChange={handleChang('address')}
            />
       </div>
       <div>
       <input 
           style={{backgroundColor : "#686868bf",
           border : "none",
           outline : "none",
           color : "white",
           width : "20%",
           padding : "10px",
           marginBottom : "10px",
           borderRadius : "5px",
         }}
         placeholder={"Email"} 
         onChange={handleChang('email')}
         type="email"
         />
       </div>
       <div>
       <input 
           style={{backgroundColor : "#686868bf",
           border : "none",
           outline : "none",
           color : "white",
           width : "20%",
           padding : "10px",
           marginBottom : "10px",
           borderRadius : "5px",
         }}
         placeholder={"Phone Number"}
         onChange={handleChang('phone')}
         type="number"
         />
       </div>
       <div>
       <input 
           style={{backgroundColor : "#686868bf",
           border : "none",
           outline : "none",
           color : "white",
           width : "20%",
           padding : "10px",
           marginBottom : "10px",
           borderRadius : "5px",
         }}
         placeholder={"Password"} 
         onChange={handleChang('password')}
         type="password"
         />
       </div>
      <div>
        <button style={{padding : 10, backgroundColor : "black",border : "none",borderRadius : 5,cursor : "pointer",paddingLeft : 30, paddingRight : 30}} onClick={() => handleSubmit()} ><span style={{color : "white"}}>Create User</span></button>
      </div>
     </div>
     </div>
    </main>
    </div>
    </div>
  )
}

export default createUserPage