import Head from 'next/head'
import React,{useState} from 'react'
import { loginUser,authincate, isAuthincated,createUser } from '../helper/auth'
import { useRouter } from 'next/router';
import Image from 'next/image'
import Script from 'next/script'

const login = () => {
    const [data, setData] = useState('')
    const router = useRouter();
    
    const handleChang = (name) => event =>{
    setData({...data, [name]: event.target.value})
    }

    function handleSubmit_login(e) {
    console.log(data)
    loginUser({data})
    .then( (res) =>  {
      console.log(res);
      if(res.user){
        authincate({token : res.token, user : res.user});
        return router.push({
          pathname: '/',
        });
      }
    })
  }

  function handleSubmit_createUser(e) {
    console.log(data)
    createUser({data})
    .then(res => {
      console.log(res);
    
      if(res.success){
        return router.push({
          pathname: '/login',
      });
      }
    })
  }

  
  // return (
  //   <>
  //    <div>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //       <link rel="preconnect" href="https://fonts.googleapis.com" />
  //       <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
  //       <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
  //     </Head>
  //     <main >
  //       <div style={{backgroundColor : "#202022", height : "100vh", textAlign : "center",alignItems : "center"}}> 
  //       <div style={{marginLeft : "50px",paddingTop : "70px",}}>
  //       <p style={{marginTop : 0,color : "#fff",fontFamily : "poppins", fontSize : 30}}>{`Login User`}</p>

  //       <div>
  //         <input 
  //           style={{backgroundColor : "#686868bf",
  //           border : "none",
  //           outline : "none",
  //           color : "white",
  //           width : "20%",
  //           padding : "10px",
  //           marginBottom : "10px",
  //           borderRadius : "5px",
  //         }}
  //         placeholder={"Title of the news"} 
  //         onChange={handleChang('email')}
  //         value={data.title}
  //         />
  //      </div>
  //       <input 
  //           style={{backgroundColor : "#686868bf",
  //           border : "none",
  //           outline : "none",
  //           color : "white",
  //           width : "20%",
  //           padding : "10px",
  //           marginBottom : "10px",
  //           borderRadius : "5px",
  //         }}
  //         placeholder={"Title of the news"} 
  //         onChange={handleChang('password')}
  //         value={data.title}
  //         />
  //     <div>
  //       <button style={{padding : 10, backgroundColor : "black",border : "none",borderRadius : 5,cursor : "pointer",paddingLeft : 30, paddingRight : 30}} onClick={() => handleSubmit()} ><span style={{color : "white"}}>Login</span></button>
  //     </div>
  //    </div>
  //    </div>
  //   </main>
  //   </div>
  // )

  return(
    <>
    <Head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {/* <Script
      src="https://kit.fontawesome.com/64d58efce2.js"
      crossorigin="anonymous"
      strategy="worker"
    >
    </Script> */}
    <title>Sign in or Sign up Form</title>
    <link rel="icon" href="/favicon.ico" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
    </Head>
    <div className="container">
      <div className="forms-container">
        <div className="signin-signup">
          <div className="sign-in-form" >
            <h2 className="title">Sign In</h2>
            <div className="input-field">
              <i className="fas fa-user"></i>
              <input 
                type="text" 
                placeholder="Username" 
                required 
                onChange={handleChang('email')}
                />
            </div>
            <div className="input-field">
              <i className="fas fa-lock"></i>
              <input 
                type="password" 
                placeholder="Password" 
                required 
                onChange={handleChang('password')}
                />
            </div>
            <input type="submit" value="Login" className="btn solid" onClick={() => handleSubmit_login()} />
          </div>
          <form className="sign-up-form">
            <h2 className="title">Sign Up</h2>
            <div className="input-field">
              <i className="fas fa-user"></i>
              <input 
                type="text" 
                placeholder="First Name" 
                required 
                onChange={handleChang('firstName')}
                value={data.title}
                />
            </div>
            <div className="input-field">
              <i className="fas fa-user"></i>
              <input 
                type="text" 
                placeholder="Last Name" 
                required 
                onChange={handleChang('lastName')}
                value={data.title}
                />
            </div>
            <div className="input-field">
              <i className="fas fa-envelope"></i>
              <input 
                type="email" 
                placeholder="Email" 
                required 
                onChange={handleChang('email')}
                value={data.title}
                />
            </div>
            <div className="input-field">
              <i className="fa fa-map-marker"></i>
              <input 
                type="text" 
                placeholder="Address" 
                required 
                onChange={handleChang('address')}
                value={data.title}
                />
            </div>
            <div className="input-field">
              <i className="fa fa-map-marker"></i>
              <input 
                type="text" 
                placeholder="Phone" 
                required 
                onChange={handleChang('phone')}
                value={data.title}
                />
            </div>
            <div className="input-field">
              <i className="fas fa-lock"></i>
              <input 
                type="password" 
                placeholder="Password" 
                required 
                onChange={handleChang('password')}/>
            </div>
            <input type="submit" className="btn" value="Sign up" onClick={() => handleSubmit_createUser()} />
          </form>
        </div>
      </div>

      <div className="panels-container">
        <div className="panel left-panel">
          <div className="content">
             <div className="logo"><a className="navbar-brand" href="#">
             <Image
                src={require('../images/logo.png')}
                alt="Picture of the author"
                width={600}
                height={200}
              />
                </a></div>
            <p style={{width : 200}}>Don't have an account?</p>
            <button className="btn transparent" id="sign-up-btn">
              Sign Up
            </button>
          </div>
          {/* <img src="img/log.svg" className="image" alt="" /> */}
          <Image
                src={require('../images/logo.png')}
                alt="Picture of the author"
                width={600}
                height={200}
              />
        </div>
        <div className="panel right-panel">
          <div className="content">
            <div className="logo"><a className="navbar-brand" href="#">
              <Image
                src={require('../images/logo.png')}
                alt="Picture of the author"
                width={600}
                height={200}
              />
                </a></div>
            <p style={{width : 200}}>Want to sign In?</p>
            <button className="btn transparent" id="sign-in-btn">
              Sign in
            </button>
          </div>
          {/* <img src="img/register.svg" className="image" alt="" /> */}
              <Image
                src={require('../images/logo.png')}
                alt="Picture of the author"
                width={600}
                height={200}
              />
        </div>
      </div>
    </div>

    {/* <Script src='javascript/index.js'></Script> */}
        <Script id="show-banner" strategy="lazyOnload">
      {`const sign_in_btn_qq = document.querySelector("#sign-in-btn");
        const sign_up_btn_qq = document.querySelector("#sign-up-btn");
        const container = document.querySelector(".container");

        sign_up_btn_qq.addEventListener("click", () => {
          container.classList.add("sign-up-mode");
        });

        sign_in_btn_qq.addEventListener("click", () => {
          container.classList.remove("sign-up-mode");
        });`}
    </Script>

  
  </>
  )
}

export default login