import Head from 'next/head'
import React,{useEffect,useState} from 'react'
import Link from 'next/link'
import { isAuthincated } from '../helper/auth'
import { useRouter } from 'next/router';

function Profile() {

  const [DATA, setDATA] = useState({});
  useEffect(() => {
    const {user} = isAuthincated()
    setDATA(user);
  }, [])
  
  return (
    <div>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap" rel="stylesheet" />
        </Head>
              <ul>
                  <li>
                    <Link href="/login">
                      <a style={{backgroundColor : "red"}} >Log Out</a>
                    </Link>
                  </li>
                  <li>
                    <Link href="/About">
                      <a>About</a>
                    </Link>    
                  </li>
                  <li>
                    <Link href="/Contact">
                      <a >Help</a>
                    </Link> 
                   </li>
                  <li>
                    <Link href="/Profile">
                      <a className='active' >Profile</a>
                    </Link> 
                  </li>
                  <li>
                    <Link href="/createPost">
                      <a>Create Post</a>
                    </Link></li>
                  <li>
                    <Link href="/">
                      <a >Home</a>
                    </Link>
                  </li>
              </ul>
        <div style={{textAlign : "center", alignItems : "center", alignContent : "center"}}>
            <p style={{fontSize : 50, fontFamily : "Poppins",fontWeight : "500", whiteSpace: 'pre-line', lineHeight : 1, color : "white"}} >
                <span style={{color : "#E42C6A"}}>H</span>
                <span style={{color : "#FCC133"}}>e</span>
                <span style={{color : "#3EB650"}}>l</span>
                <span style={{color : "#E12B38"}}>l</span>
                <span style={{color : "#3778C2"}}>o</span>
                {`, \n ${DATA.firstName} ${DATA.lastName}`}</p>
                <p style={{color : "white", fontSize : 18}}>Email : {DATA.email} </p>
                <p style={{color : "white", fontSize : 18}}>Phone : {DATA.phone}</p>
                <p style={{color : "white", fontSize : 18}}>Address : {DATA.address}</p>
        </div>
    </div>
  )
}

export default Profile